In [1]:
from utils import *

C:\Users\bdr\anaconda3\envs\caienv\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\bdr\anaconda3\envs\caienv\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\bdr\anaconda3\envs\caienv\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\bdr\anaconda3\envs\caienv\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\bdr\anaconda3\envs\caienv\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\bdr\anaconda3\envs\caienv\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
C:\Users\bdr\anaconda3\envs\caienv\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\bdr\anaconda3\envs\caienv\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\bdr\anaconda3\envs\caienv\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\bdr\anaconda3\envs\caienv\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\bdr\anaconda3\envs\caienv\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\bdr\anaconda3\envs\caienv\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

In [6]:
df = pd.read_csv(r"H:\tst\Log21.10.22_04_T-maze.csv", delimiter=';')

In [7]:
df = df.loc[38973:]

In [9]:
df.to_csv(r"H:\raw.csv",index=False,sep=';')

In [10]:
bdata = pd.read_csv("H:raw.csv", delimiter=';')

In [11]:
bdata

,DateTime,xPosComp,yPosComp,ViewDir,xPos,yPos,Unnamed: 6
0,44491.438657,0.000000,0.000,0.0,0.000000,0.00,NaN
1,44491.438658,0.000000,0.000,0.0,0.000000,0.00,NaN
2,44491.438658,0.000000,0.000,0.0,0.000000,0.00,NaN
3,44491.438659,0.000000,0.000,0.0,0.000000,0.00,NaN
4,44491.438659,0.000000,0.000,0.0,0.000000,0.00,NaN
...,...,...,...,...,...,...,...
42415,44491.463558,1000.000061,565.099,0.0,-247879.194333,201145.90,NaN
42416,44491.463559,1000.000061,564.434,0.0,-247878.501306,201146.21,NaN
42417,44491.463559,1000.000061,564.434,0.0,-247878.501306,201146.21,NaN
42418,44491.463560,1000.000061,564.434,0.0,-247878.501306,201146.21,NaN
42419,44491.463561,1000.000061,564.434,0.0,-247878.501306,201146.21,NaN

In [57]:
bdata_process(r"H:", r"H:")

start processing H:raw.csv

,t,trial,bin,type,choice,rewarded,rundir,speed,stimulus,pretype,prechoice,prerewarded,x,y,viewdir,xreal,yreal,isimaged
4043,0.000000e+00,0,0.0,AA,R,0,0.00,0.000000,A,None,None,NaN,3000.000000,2.022000,0.0,-324.449596,3675.63,True
4044,5.100179e+01,0,0.0,AA,R,0,10.26,10.616908,A,None,None,NaN,3000.000000,5.714000,0.0,-327.179272,3685.89,True
4045,1.010015e+02,0,0.0,AA,R,0,11.06,12.781735,A,None,None,NaN,3000.000000,10.508000,0.0,-333.586232,3696.95,True
4046,1.520033e+02,0,0.0,AA,R,0,11.15,12.613743,A,None,None,NaN,3000.000000,17.905000,0.0,-339.484030,3708.10,True
4047,2.030051e+02,0,0.0,AA,R,0,9.26,9.674182,A,None,None,NaN,3000.000000,19.829000,0.0,-342.284423,3717.36,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41294,1.890144e+06,131,30.0,AA,R,0,-3.17,15.891270,A,BB,R,1.0,1485.248019,1000.863037,90.0,-247303.232654,199150.57,False
41295,1.890194e+06,131,30.0,AA,R,0,-2.21,9.139144,A,BB,R,1.0,1497.101019,1000.863037,90.0,-247312.100566,199148.36,False
41296,1.890245e+06,131,30.0,AA,R,0,-1.62,1.835411,A,BB,R,1.0,1496.592019,1000.863037,90.0,-247311.237819,199146.74,False
41297,1.890296e+06,131,30.0,AA,R,0,-1.31,2.303897,A,BB,R,1.0,1494.159019,1000.863037,90.0,-247309.342603,199145.43,False
41298,1.890347e+06,131,30.0,AA,R,0,-1.72,3.262357,A,BB,R,1.0,1496.167019,1000.863037,90.0,-247312.114710,199143.71,False

In [58]:
df = pd.read_csv(r"H:\bdata.csv", delimiter=',')

In [65]:
df2 = df[df.isimaged]

In [63]:
list(trial_info(df2).trial)

[28, 67, 100, 117, 129, 130, 131]

In [66]:
d1 = df2[df2.trial<28]
d2 = df2.loc[(28<df2.trial) & (df2.trial<67)]
d3 = df2.loc[(67<df2.trial) & (df2.trial<100)]
d4 = df2.loc[(100<df2.trial) &(df2.trial<117)]
d5 = df2.loc[(117<df2.trial) & (df2.trial<129)]

In [38]:
xmls = list(Path(r"H:\tst").glob('*xml'))

In [39]:
xmls

[WindowsPath('H:/tst/recording_20211022_103405.xml'),
 WindowsPath('H:/tst/recording_20211022_103739.xml'),
 WindowsPath('H:/tst/recording_20211022_104011.xml'),
 WindowsPath('H:/tst/recording_20211022_104626.xml'),
 WindowsPath('H:/tst/recording_20211022_105244.xml'),
 WindowsPath('H:/tst/recording_20211022_105917.xml')]

In [40]:
frames = []
for p in xmls:
    root = ET.parse(p).getroot()
    for chd in root[0]:
        if chd.items()[0][1] == "dropped_count":
            if int(chd.text) > 0:
                frames.append(None)
                break
        if chd.items()[0][1] == "frames":
            frames.append(int(chd.text))
            break

In [72]:
np.array(frames)*50

array([213250, 147350, 364800, 367700, 371550, 290350])

In [80]:
np.sum([213250, 147350])

360600

In [78]:
ds = [d1, d2, d3, d4, d5]

In [76]:
d1.t

0            0.000000
1           51.001785
2          101.001514
3          152.003299
4          203.005085
            ...
7098    360459.002783
7099    360510.004568
7100    360560.004297
7101    360611.006082
7102    360661.005811
Name: t, Length: 7103, dtype: float64

In [79]:
for d in ds:
    print((d.t.iloc[-1]-d.t.iloc[0]))

360661.00581083447
364856.00292216986
367788.99722266966
371557.99898318946
290348.00331573933

In [55]:
def bdata_process(raw_behavior_root, processed_root, task="", name="", day=""):
    #original behavior data
    filename = list((Path(raw_behavior_root)/name/task/day).glob('*.csv'))[0]
    print(f"start processing {filename}")
    bdata = pd.read_csv(filename, delimiter=';')

    #timepoints of starts of trials
    tristarts = np.where(bdata.yPosComp.diff() < -500)[0]
    
    #a timepoint where the first trial started
    expstart =  np.where(bdata.yPosComp.diff() < -3000)[0]
    if len(expstart) != 1:
        print(f"error!, {name},{task},{day}")

    #cut off unnecessary timepoints
    bdata2 = bdata.iloc[tristarts[0]:tristarts[-1],:]

    #make behavioral variables for each timepoint
    t = (bdata2.DateTime - bdata2.iloc[0].DateTime) * 1000* 60 * 60 * 24 #time(ms)
    trials = [] #trial number of current timepoint
    typs = [] #trial type ("AA",..,"BA") of current timepoint
    choices = [] #choice of the trial of current timepoint
    rewardeds = [] #1 if reward was derivered in the trial of current timepoint, else 0
    pretyps = [] #trial type ("AA",..,"BA") of the previous trial of current timepoint
    prechoices = [] #choice of the previous trial of current timepoint
    prerewardeds = [] #1 if reward was derivered in the previous trial of current timepoint, else 0
    bins = [] #spatial bin of current timepoint
    speeds = [] #speed
    rundirs = [] #rundir(differences of yPos between adjacent timepoints)
                 #rundirs<0 means left turn and rundirs>0 means right turn
    for i in range(len(tristarts)-1):
        if i == 0:
            pretyps += [None] * (tristarts[i+1] - tristarts[i])
            prechoices += [None] * (tristarts[i+1] - tristarts[i])
            prerewardeds += [None] * (tristarts[i+1] - tristarts[i])
        else:
            pretyps += [typ] * (tristarts[i+1] - tristarts[i])
            prechoices += [choice] * (tristarts[i+1] - tristarts[i])
            prerewardeds += [rewarded] * (tristarts[i+1] - tristarts[i])
        start = bdata2.loc[tristarts[i],:]
        end = bdata2.loc[tristarts[i+1]-1,:]
        choice = 'L' if end.ViewDir > 180 else 'R'
        type1 = 'A' if start.xPosComp > 0 else 'B'
        type2 = 'A' if end.xPosComp > 0 else 'B'
        typ = type1 + type2
        rewarded = 1 if (choice, type2) in (('L','A'),('R','B')) else 0
        trials += [i] * (tristarts[i+1] - tristarts[i])
        typs += [typ] * (tristarts[i+1] - tristarts[i])
        choices += [choice] * (tristarts[i+1] - tristarts[i])    
        rewardeds += [rewarded] * (tristarts[i+1] - tristarts[i])
        gbdata = bdata2.loc[tristarts[i]:tristarts[i+1]-1,:]
        viewdir = np.where(gbdata.ViewDir < 180, gbdata.ViewDir, gbdata.ViewDir-360)
        tjuncX = gbdata.iloc[np.where(gbdata.ViewDir==0)[0][-1]].xPosComp
        bin1 = np.where(abs(viewdir) < 90, np.clip(gbdata.yPosComp, 0, 1000)//50, 0)
        bin2 = np.where(abs(viewdir) == 90, np.clip(abs(gbdata.xPosComp - tjuncX), 0, 499)//50 + 21, 0)
        bins += list(bin1+bin2)
        rundirs += list(np.diff(gbdata.yPos, prepend=gbdata.yPos.iloc[0]))
        speeds += list(np.sqrt(np.diff(gbdata.xPos, prepend=gbdata.xPos.iloc[0])**2 \
                               + np.diff(gbdata.yPos, prepend=gbdata.yPos.iloc[0])**2))

    #convert 0 < viewdir < 360 to -90 < viewdir < 90 (counterclockwise)
    viewdir = np.where(bdata2.ViewDir < 180, bdata2.ViewDir, bdata2.ViewDir-360)

    #True if the current trial was imaged.
    imaging = np.where(abs(bdata2.xPosComp) > 2000, True, False)

    #visual stimuli of current timepoint
    stimulus = np.where(bdata2.xPosComp > 0, "A", "B")

    bdata3 = pd.DataFrame({'t': t, 
                           'trial' : trials,
                           'bin' : bins,
                           'type' : typs,
                           'choice' : choices,
                           'rewarded' : rewardeds,
                           'rundir' : rundirs,
                           'speed' :speeds,
                           'stimulus' : stimulus,
                           'pretype' : pretyps,
                           'prechoice' : prechoices,
                           'prerewarded' : prerewardeds,
                           'x' : bdata2.xPosComp,
                           'y' : bdata2.yPosComp,
                           'viewdir' : viewdir,
                           'xreal' : bdata2.xPos,
                           'yreal' : bdata2.yPos,
                           'isimaged' : imaging})
    
    bdata3.to_csv(Path(processed_root)/name/task/day/"bdata.csv", index=False)
    return bdata3